### ISSUE TITLE
Provide authentication through an AuthenticationProvider interface

### ISSUE THREAD

**Issue by tcr-ableton** [AbletonAG/go-travis#2]
@thoas noticed that in it's current state the Authentication is a mutable process. He suggested we could enhance this by creating an AuthenticationProvider interface, implemented a TravisAuthProvider and GithubAuthProvider, to make the authentication process more plain and immutable.

**Comment by tcr-ableton** [comment]
Implementation Idea:

**interface**

``` go
type AuthenticationProvider interface {
    Authenticate() (AccessToken, error)
}
```

**usage**

``` go
travis.NewClient(TRAVIS_API_DEFAULT_URL, GithubAuthProvider("mytoken"))
// or
travis.NewClient(TRAVIS_API_DEFAULT_URL, TravisAuthProvider())
```

**Comment by tcr-ableton** [comment]
A possible implementation of it would consist in the following:

interface implementation

``` go
type GithubAuthProvider struct {
        GithubToken string
}

type TravisAuthProvider struct {
        TravisToken string
}

func (*GithubAuthProvider) Authenticate() (AccessToken, error) {
    // get and return a travis token from the api using the github token 
}

func (*TravisAuthProvider) Authenticate() (AccessToken, error) {
    // return the TravisToken
}
```

client implementation

``` go
func (c *Client) Authenticate(auth AuthenticationProvider) error {
    c.client.Headers["Authorization"] = "token " + auth.Authenticate()
}
```

**Comment by tcr-ableton** [comment]
Spotted a problem in the implementation of this design: the GithubAuthProvider would need the client instance to query travis for a travis token. Which would actually lead to an impossible design as the client constructor would need to pass himself to the provider.

``` go
# Not possible
client := NewClient(TRAVIS_API_DEFAULT_URL, GithubAuthProvider(clientIHaventBuiltJustYet, token))
```

**Comment by tcr-ableton** [comment]
A workaround could be to add a client attribute to the provider when relevant. To pass the provider to the constructor with its client attribute uninitialized. And when calling `Client.Authenticate` initializing the provider client attribute, and calling its `Authenticate` method.

``` go
func (c *Client) Authenticate(auth AuthenticationProvider) error {
    auth.client = c.client
    c.client.Headers["Authorization"] = "token " + auth.Authenticate()
}
```

But this sounds super hacky, and introduces mutability, which was exactly the aspect of current implementation we are trying to get rid of.

**Comment by nsh-ableton** [comment]
Hey @tcr-ableton, do you think it would make sense to close this?

**Comment by mst-ableton** [comment]
Given the state of things, I don't think this issue will be addressed anytime soon.
