### ISSUE TITLE
No way to set base http.Transport/http.Client

### ISSUE THREAD

**Issue by broady** [AbletonAG/go-travis#7]
Because of this, this library cannot be used from Google App Engine (which requires using the `urlfetch` client).

**Comment by tcr-ableton** [comment]
Hey @broady thanks for reporting this! We surely need to address that. I think your fix is good, although I'd like the exposed attribute name to be a bit more obvious like `HTTPClient` what do you think?

If that works for you, please submit a pull request!

Cheers

**Comment by nsh-ableton** [comment]
Hi! Can I help to close this issue somehow? 😸

**Comment by dmitshur** [comment]
@nsh-ableton, it looks like @broady made a commit that nearly resolves the issue, see https://github.com/broady/go-travis/commit/bd5bbab6364d388ce9b0a3e4f3f5496bf657af4a. You could take it, amend it to apply @tcr-ableton's suggestion of using `HTTPClient` as the name above, and make a PR.

There are 2 other new commits on that fork, that [look nice](https://github.com/Ableton/go-travis/compare/master...broady:master) and would maybe worth being upstreamed.

**Comment by nsh-ableton** [comment]
Thanks for the input, @shurcooL!

**Comment by mst-ableton** [comment]
Thanks for your input on this, and sorry for the extremely late reply. Unfortunately I don't think we'll be able to address this issue in this repo. I've forwarded it along to @shuheiktgw to see if it's still relevant in their fork.

**Comment by shuheiktgw** [comment]
@nsh-ableton Thank you for your heads up!

I fixed the problem on https://github.com/shuheiktgw/go-travis/pull/7, so if anyone still has the same problem, please consider using [shuheiktgw/go-travis](https://github.com/shuheiktgw/go-travis) 's v0.1.7 or above! 👍
