### ISSUE TITLE
404 link in README.

### ISSUE THREAD

**Issue by dmitshur** [AbletonAG/go-travis#9]
The README has a [Roadmap section](https://github.com/Ableton/go-travis#roadmap) (likely originally taken from go-github):

> ## Roadmap
> 
> This library is being initially developed for internal applications at
> [Ableton](http://ableton.com). Therefore API methods are implemented in the order that they are
> needed by our applications. Eventually, we would like to cover the entire
> Travis API, so contributions are of course [always welcome](https://github.com/Ableton/go-travis/blob/master/CONTRIBUTING.md).

But the "contributing" link is broken because there's no `CONTRIBUTING.md` file in the repo.

**Comment by tcr-ableton** [comment]
Hey @shurcooL thanks for reporting that, I'll add a contributing.md file straight away :-)

**Comment by tcr-ableton** [comment]
There is now a contributions guideline in place: https://github.com/Ableton/go-travis/blob/master/CONTRIBUTING.md

Please note that we will soon require a CLA for contributions.

Cheers
